version: '3'

services:
  vstsdockerbuild.webapp:
    image: sparreio.azurecr.io/vstsdockerbuild.webapp
   
  vstsdockerbuild.pongservice:
    image: sparreio.azurecr.io/vstsdockerbuild.pongservice

  vstsdockerbuild.integrationtests:
      entrypoint: dotnet test --logger trx --results-directory /var/temp
      volumes:
        - /opt/vsts/work/_temp:/var/temp
