version: '3'

services:
  vstsdockerbuild.tests:
    environment: 
      - BLOWUP
    image: vstsdockerbuild.tests
    build:
      context: .
      dockerfile: tests/VstsDockerBuild.Tests/Dockerfile
    entrypoint: dotnet test --logger trx --results-directory /var/temp
    volumes:
      - /opt/vsts/work/_temp:/var/temp