version: '3.4'

services:
  ci-build:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./projetodocker.sln && dotnet publish ./projetodocker.sln -c Release -o ./obj/Docker/publish"
